[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Simon-A-P <simon.pfaus@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
